services:
  web:
    container_name: "web"
    image: "nginx"
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "/etc/ssl:/etc/ssl"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - notbyte
  notbyte:
    container_name: "notbyte"
    image: "ghcr.io/not-byte/notbyte-website"
    restart: unless-stopped

networks:
  default:
    name: web
    ipam:
      config:
        - subnet: 10.0.0.0/27
          ip_range: 10.0.0.0/27
          gateway: 10.0.0.1