services:
  notbyte:
    container_name: "notbyte"
    image: "ghcr.io/not-byte/notbyte-website"
    restart: unless-stopped
  web:
    container_name: "web"
    image: "nginx"
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
#    volumes:
#      - "/etc/ssl:/etc/ssl"
#      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
#      - "./nginx/conf.d:/etc/nginx/conf.d"
#    links:
#      - notbyte
#    networks:
#      - web

#networks:
#  web:
#    name: web
#    ipam:
#      config:
#        - subnet: 10.0.0.0/16
#          ip_range: 10.0.0.0/16
#          gateway: 10.0.0.1
#  bridge:
#    name: bridge
#    external: true