services:
  web:
    container_name: "web"
    image: "nginx"
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "/etc/ssl:/etc/ssl"
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - notbyte
  notbyte:
    container_name: "notbyte"
    image: "ghcr.io/not-byte/notbyte-website"
    restart: always
    depends_on:
      - web

networks:
  default:
    name: web
    ipam:
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.0.0/16
          gateway: 10.0.0.1
